apiVersion: v1
kind: Service
metadata:
  name: metastore
spec:
  selector:
    app: metastore
  ports:
    - name: postgre
      protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: 10.96.0.20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metastore
  template:
    metadata:
      labels:
        app: metastore
    spec:
      containers:
        - name: metastore
          image: postgres:11
          env:
            - name: POSTGRES_PASSWORD
              value: jupyter
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: metastore-data
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d/init.sql
      volumes:
        - name: metastore-data
          emptyDir: {}
        - name: init
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  selector:
    app: master
  ports:
    - name: master-4040
      protocol: TCP
      port: 4040
      targetPort: 4040
    - name: master-8020
      protocol: TCP
      port: 8020
      targetPort: 8020
    - name: master-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: master-8088
      protocol: TCP
      port: 8088
      targetPort: 8088
    - name: master-9870
      protocol: TCP
      port: 9870
      targetPort: 9870
    - name: master-10000
      protocol: TCP
      port: 10000
      targetPort: 10000
  clusterIP: 10.96.0.11
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: zed378/hadoop-hive-spark-master
          env:
            - name: SPARK_MASTER_HOST
              value: 10.96.0.11
            - name: SPARK_LOCAL_IP
              value: 10.96.0.11
            - name: SPARK_LOCAL_HOSTNAME
              value: master
          ports:
            - containerPort: 4040
            - containerPort: 8020
            - containerPort: 8080
            - containerPort: 8088
            - containerPort: 9870
            - containerPort: 10000
          volumeMounts:
            - name: namenode
              mountPath: /opt/hadoop/dfs/name
      volumes:
        - name: namenode
          emptyDir: {}
---
# next line
apiVersion: v1
kind: Service
metadata:
  name: worker1
spec:
  selector:
    app: worker1
  ports:
    - name: worker1-8042
      protocol: TCP
      port: 8042
      targetPort: 8042
    - name: worker1-8081
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: worker1-9864
      protocol: TCP
      port: 9864
      targetPort: 9864
  clusterIP: 10.96.0.12
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker1
  template:
    metadata:
      labels:
        app: worker1
    spec:
      containers:
        - name: worker1
          image: zed378/hadoop-hive-spark-worker
          env:
            - name: SPARK_MASTER_HOST
              value: 10.96.0.11
            - name: SPARK_LOCAL_IP
              value: 10.96.0.12
            - name: SPARK_LOCAL_HOSTNAME
              value: worker1
          ports:
            - containerPort: 8042
            - containerPort: 8081
            - containerPort: 9864
          volumeMounts:
            - name: datanode1
              mountPath: /opt/hadoop/dfs/data
      volumes:
        - name: datanode1
          emptyDir: {}
---
# next line
apiVersion: v1
kind: Service
metadata:
  name: worker2
spec:
  selector:
    app: worker2
  ports:
    - name: worker2-8042
      protocol: TCP
      port: 8043
      targetPort: 8042
    - name: worker2-8081
      protocol: TCP
      port: 8082
      targetPort: 8081
    - name: worker2-9864
      protocol: TCP
      port: 9865
      targetPort: 9864
  clusterIP: 10.96.0.13
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker2
  template:
    metadata:
      labels:
        app: worker2
    spec:
      containers:
        - name: worker2
          image: zed378/hadoop-hive-spark-worker
          env:
            - name: SPARK_MASTER_HOST
              value: 10.96.0.11
            - name: SPARK_LOCAL_IP
              value: 10.96.0.13
            - name: SPARK_LOCAL_HOSTNAME
              value: worker2
          ports:
            - containerPort: 8043
            - containerPort: 8082
            - containerPort: 9865
          volumeMounts:
            - name: datanode2
              mountPath: /opt/hadoop/dfs/data
      volumes:
        - name: datanode2
          emptyDir: {}
---
# next line
apiVersion: v1
kind: Service
metadata:
  name: history
spec:
  selector:
    app: history
  ports:
    - name: history-18080
      protocol: TCP
      port: 18080
      targetPort: 18080
    - name: history-19888
      protocol: TCP
      port: 19888
      targetPort: 19888
  clusterIP: 10.96.0.14
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers:
        - name: history
          image: zed378/hadoop-hive-spark-history
          env:
            - name: SPARK_MASTER_HOST
              value: 10.96.0.11
            - name: SPARK_LOCAL_IP
              value: 10.96.0.14
            - name: SPARK_LOCAL_HOSTNAME
              value: history
          ports:
            - containerPort: 18080
            - containerPort: 19888

---
# next line
apiVersion: v1
kind: Service
metadata:
  name: jupyter
spec:
  selector:
    app: jupyter
  ports:
    - name: jupyter-8888
      protocol: TCP
      port: 8888
      targetPort: 8888
  clusterIP: 10.96.0.15
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: jupyter
          image: zed378/hadoop-hive-spark-jupyter
          env:
            - name: SPARK_MASTER_HOST
              value: 10.96.0.11
            - name: SPARK_LOCAL_IP
              value: 10.96.0.15
            - name: SPARK_LOCAL_HOSTNAME
              value: jupyter
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: notebook
              mountPath: /notebook
      volumes:
        - name: notebook
          emptyDir: {}
---
# next line
